### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by CR7SON** [joaoviictorti/shadow-rs#4]
hello

Just as protection is applied to processes and threads, can it also be applied to drivers?

thank you

**Comment by joaoviictorti** [comment]
Hello, what kind of protection do you mean for the drivers? deleting files? getting a handle?

**Comment by CR7SON** [comment]
![Untitled](https://github.com/user-attachments/assets/35566d8f-0895-422f-b730-8824e3c8a533)

Getting a handle.

I want to prevent information from being obtained from winobj as shown in the picture above.

Is it possible? thank you.

**Comment by joaoviictorti** [comment]
Hi, sorry for the delay.

Yes, it is possible to restrict access to the driver using tools such as WinObj. You can do this using two methods:

* Setting up a security descriptor:
You can set specific permissions on the device object so that only SYSTEM or Administrators can access it. This is done by applying a custom security descriptor during driver initialization. For example, you can configure it to deny access to unauthorized users or groups.

* Restrict access by PID:
You can intercept IRP_MJ_CREATE requests (triggered by calls such as CreateFile) and check the caller's process ID. If the calling process is not authorized (based on a predefined PID), you can deny the request, ensuring that only specific processes can interact with the driver.

**Comment by joaoviictorti** [comment]
But since in this case the person can access WinObj with elevated access, I believe that the last choice can help

**Comment by CR7SON** [comment]
Good! thank you
